<?php

/**
 * @file
 * Contains helhist_search.module.
 */

/**
 * Implements hook_theme().
 */
function helhist_search_theme() {
  return [
    'search_frontend' => [
      'variables' => [],
      'template' => 'search-frontend',
    ],
    'frontpage_search' => [
      'variables' => [
        'search_page_path' => NULL,
      ],
      'template' => 'frontpage-search',
    ],
    'header_search' => [
      'variables' => [
        'search_page_path' => NULL,
      ],
      'template' => 'header-search',
    ],
    'react_search' => [
      'variables' => [],
      'template' => 'react-search',
    ],
  ];
}
