footer_settings:
  footer_top_content:
    value: "<p><a href=\"https://numerot.hel.fi/\">Hae yhteystietoja ja numeroita</a></p>\r\n\r\n<p><a class=\"hds-button hds-button--secondary\" href=\"tel:+35893101691\"><span class=\"hds-button__label\">Helsinki-info 09 310 1691</span></a></p>\r\n"
    format: full_html
  footer_top_title: Yhteystiedot
