footer_settings:
  footer_top_content:
    format: full_html
    value: '<p><a class="hds-button hds-button--secondary" href="https://www.hel.fi/helsinki/fi/kaupunki-ja-hallinto/osallistu-ja-vaikuta/palaute/"><span class="hds-button__label">Anna palautetta tai kysy</span></a></p>'
  footer_top_title: Yhteystiedot
site_settings:
  theme_color: metro
  koro: vibration
