settings:
  default_form_open_message: 'Tätä lomaketta ei ole vielä avattu lähetyksille.'
  default_submit_button_label: Lähetä
  default_reset_button_label: Palauta
  default_delete_button_label: Poista
  default_form_confidential_message: 'Tämä lomake on luottamuksellinen. Sinun täytyy <a href="[site:login-url]/logout?destination=[current-page:url:relative]">kirjautua ulos</a> lähettääksesi se.'
  default_wizard_start_label: Alkaa
  default_wizard_confirmation_label: Valmis
  default_wizard_toggle_show_label: 'Näytä kaikki'
  default_wizard_toggle_hide_label: 'Piilota kaikki'
  default_preview_next_button_label: Esikatselu
  default_preview_label: Esikatselu
  default_draft_button_label: 'Tallenna keskeneräinen'
  default_draft_saved_message: 'Tiedot tallennettu. Voit palata tähän lomakkeeseen myöhemmin ja palauttaa nykyiset tiedot.'
  default_confirmation_message: 'Lisätty uusi lähetys lomakkeelle [webform:title].'
  dialog_options:
    narrow:
      title: Kapea
    normal:
      title: Normaali
    wide:
      title: Leveä
element:
  default_more_title: Lisää
  default_section_title_tag: h2
