<?php

/**
 * @file
 * Provides KoRe (koulurekisteri) React search template and theme.
 */

declare(strict_types=1);

use Drupal\Core\Site\Settings;

/**
 * Implements hook_theme().
 */
function helhist_kore_search_theme() {
  return [
    'kore_react_search' => [
      'variables' => [
        'ELASTIC_PROXY_URL' => '',
      ],
      'template' => 'kore-react-search',
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function helhist_kore_search_preprocess_kore_react_search(array &$variables): void {
  $variables['ELASTIC_PROXY_URL'] = $variables['ELASTIC_PROXY_URL']
    ?? Settings::get('elasticsearch_proxy_url', '');
}
