<?php

/**
 * @file
 * Provides Helhist Kore search related modifications.
 */

declare(strict_types=1);

use Drupal\Core\Form\FormStateInterface;

/**
 * @file
 * Primary module hooks for helhist_kore_admin module.
 */

/**
 * Implements hook_views_data().
 */
function helhist_kore_admin_views_data() {
  $data['views']['kore_search_content'] = [
    'title' => t('Kore Search Content'),
    'help' => t('Displays the configured Kore Search title and text content.'),
    'area' => [
      'id' => 'kore_search_content',
      'label' => t('Kore Search Content'),
    ],
  ];
  return $data;
}

/**
 * Implements hook_form_alter().
 */
function helhist_kore_admin_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if (strpos($form_id, 'views_exposed_form') === 0) {
    $view = $form_state->get('view');
    if ($view && $view->id() === 'kore_search') {
      // Place the Kore Search Content block above the kore search exposedform.
      $block_manager = \Drupal::service('plugin.manager.block');
      $block_config = [];
      $block_plugin = $block_manager->createInstance('kore_search_content_block', $block_config);
      $block_content = $block_plugin->build();
      $form['#prefix'] = \Drupal::service('renderer')->render($block_content);
    }
  }
}
