dependencies:
  module:
    - field_group
    - geofield_map
    - select2
    - text
third_party_settings:
  field_group:
    group_historiaportaali_meta:
      children:
        - field_phenomena
        - field_neighbourhoods
        - group_year
        - field_keywords
      label: 'Historia.helsinki metatietokentät'
      region: content
      parent_name: ''
      weight: 10
      format_type: details
      format_settings:
        classes: ''
        id: ''
        open: false
        description: ''
        required_fields: true
    group_finna_meta:
      children:
        - field_finna_id
        - field_formats
        - field_authors
        - field_copyrights
        - field_languages
        - group_location
      label: 'Finna.fi metatietokentät'
      region: content
      parent_name: ''
      weight: 12
      format_type: details
      format_settings:
        classes: ''
        id: ''
        open: false
        description: ''
        required_fields: true
    group_location:
      children:
        - field_buildings
        - field_buildings_info
      label: Säilytyspaikka
      region: content
      parent_name: group_finna_meta
      weight: 24
      format_type: fieldset
      format_settings:
        classes: ''
        id: ''
        description: ''
        required_fields: true
    group_year:
      children:
        - field_start_year
        - field_end_year
      label: Aikakausi
      region: content
      parent_name: group_historiaportaali_meta
      weight: 20
      format_type: fieldset
      format_settings:
        classes: ''
        id: ''
        description: ''
        required_fields: true
    group_geolocation:
      children:
        - field_geolocation
      label: 'Sijainti kartalla'
      region: content
      parent_name: ''
      weight: 11
      format_type: details
      format_settings:
        classes: ''
        id: ''
        open: true
        description: ''
        required_fields: true
content:
  field_authors:
    type: select2_entity_reference
    weight: 21
    region: content
    settings:
      width: 100%
      autocomplete: true
      match_operator: CONTAINS
      match_limit: 10
    third_party_settings: {  }
  field_buildings:
    type: select2_entity_reference
    weight: 12
    region: content
    settings:
      width: 100%
      autocomplete: true
      match_operator: CONTAINS
      match_limit: 10
    third_party_settings: {  }
  field_buildings_info:
    type: string_textfield
    weight: 13
    region: content
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
  field_copyrights:
    type: select2_entity_reference
    weight: 22
    region: content
    settings:
      width: 100%
      autocomplete: true
      match_operator: CONTAINS
      match_limit: 10
    third_party_settings: {  }
  field_end_year:
    type: number
    weight: 28
    region: content
    settings:
      placeholder: ''
    third_party_settings: {  }
  field_finna_id:
    type: string_textfield
    weight: 19
    region: content
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
  field_formats:
    type: select2_entity_reference
    weight: 20
    region: content
    settings:
      width: 100%
      autocomplete: true
      match_operator: CONTAINS
      match_limit: 10
    third_party_settings: {  }
  field_geolocation:
    type: geofield_map
    weight: 5
    region: content
    settings:
      html5_geolocation: false
      default_value:
        lat: 0.0
        lon: 0.0
      map_library: leaflet
      map_google_api_key: ''
      map_google_places:
        places_control: false
        places_additional_options: ''
      map_dimensions:
        width: 100%
        height: 450px
      map_type_google: roadmap
      map_type_leaflet: OpenStreetMap_Mapnik
      map_type_selector: true
      zoom_level: 5
      zoom:
        start: 6
        focus: 12
        min: 0
        max: 22
      click_to_find_marker: false
      click_to_place_marker: false
      hide_coordinates: false
      geoaddress_field:
        field: '0'
        hidden: false
        disabled: true
      map_geocoder:
        control: 1
        settings:
          providers:
            openstreetmap:
              weight: 0
              checked: true
          min_terms: 4
          delay: 800
          options: ''
    third_party_settings: {  }
  field_image_caption:
    type: string_textarea
    weight: 3
    region: content
    settings:
      rows: 5
      placeholder: ''
    third_party_settings: {  }
  field_keywords:
    type: select2_entity_reference
    weight: 21
    region: content
    settings:
      width: 100%
      autocomplete: true
      match_operator: CONTAINS
      match_limit: 10
    third_party_settings: {  }
  field_languages:
    type: select2_entity_reference
    weight: 23
    region: content
    settings:
      width: 100%
      autocomplete: true
      match_operator: CONTAINS
      match_limit: 10
    third_party_settings: {  }
  field_neighbourhoods:
    type: select2_entity_reference
    weight: 19
    region: content
    settings:
      width: 100%
      autocomplete: true
      match_operator: CONTAINS
      match_limit: 10
    third_party_settings: {  }
  field_phenomena:
    type: select2_entity_reference
    weight: 18
    region: content
    settings:
      width: 100%
      autocomplete: true
      match_operator: CONTAINS
      match_limit: 10
    third_party_settings: {  }
  field_start_year:
    type: number
    weight: 27
    region: content
    settings:
      placeholder: ''
    third_party_settings: {  }
  field_transcript:
    type: text_textarea
    weight: 4
    region: content
    settings:
      rows: 5
      placeholder: ''
    third_party_settings: {  }



