track_enabled_base_fields: false
local_task_enabled_entity_types:
  - paragraphs_library_item
usage_controller_items_per_page: 25
edit_warning_message_entity_types:
  - paragraphs_library_item
delete_warning_message_entity_types:
  - paragraphs_library_item
_core:
  default_config_hash: Bpksy-WBWXBfa88auy0xIMU9sbHkNFEFrqoskMDlMmo
