# The services of the project.

mysqldb3:
  type: mariadb:10.11
  disk: 3584
rediscache:
  type: redis:3.2
elasticsearch:
  type: elasticsearch:7.9
  disk: 256
#solrsearch:
#    type: solr:6.6
#    disk: 1024
