# The services of the project.

mysqldb:
  type: mysql:10.11
  disk: 3584
  configuration:
    properties:
      default_charset: utf8mb4
      default_collation: utf8mb4_swedish_ci
rediscache:
  type: redis:3.2
elasticsearch:
  type: elasticsearch:7.9
  disk: 256
#solrsearch:
#    type: solr:6.6
#    disk: 1024
