<?php

/**
 * @file
 * Provides Helhist custom tokens.
 */

declare(strict_types=1);

use Drupal\Core\Render\BubbleableMetadata;
use Drupal\Core\Render\Markup;
use Drupal\views\ViewExecutable;

/**
 * Implements hook_token_info().
 */
function helhist_tokens_token_info() {
  $info['tokens']['view']['search_result_info'] = [
    'name' => t('Search result info'),
    'description' => t('Display information about currently executed search.'),
  ];

  return $info;
}

/**
 * Implements hook_tokens().
 */
function helhist_tokens_tokens($type, $tokens, array $data, array $options, BubbleableMetadata $bubbleable_metadata) {
  $replacements = [];

  foreach ($tokens as $name => $original) {
    switch ($name) {
      case 'search_result_info':
        $replacements[$original] = '';

        if (!isset($data['view']) || !$data['view'] instanceof ViewExecutable) {
          break;
        }

        $view = $data['view'];

        $num_of_results = $view->total_rows;
        $search_query = $view->exposed_raw_input['s'] ?? '';

        $token_content = t(
          '@num_of_results results',
          ['@num_of_results' => $num_of_results],
          ['context' => 'Search']
        );

        if ($search_query) {
          $token_content .= ' ' . t(
            'for keyword: @keyword',
            ['@keyword' => $search_query],
            ['context' => 'Search']
          );
        }

        $replacements[$original] = Markup::create('<h3>' . $token_content . '</h3>');
        break;
    }
  }

  return $replacements;
}
