footer_settings:
  footer_top_content:
    format: full_html
    value: "<p><a class=\"hds-button hds-button--secondary\" href=\"https://www.hel.fi/Helsinki/sv/stad-och-forvaltning/delta/feedback/\"><span class=\"hds-button__label\">Ge Feedback Och Fråga</span></a></p>\r\n"
  footer_top_title: Kontaktinformation
site_settings:
  theme_color: metro
  koro: vibration
