settings:
  default_form_close_message: 'Tyvärr... Detta formulär är stängt för nya bidrag.'
  default_submit_button_label: Skicka
  default_reset_button_label: Återställ
  default_delete_button_label: Radera
  default_form_access_denied_message: 'Please login to access this form.'
  default_wizard_prev_button_label: '< Föregående'
  default_wizard_next_button_label: 'Nästa >'
  default_wizard_start_label: Från
  default_wizard_confirmation_label: Slutförd
  default_preview_next_button_label: Förhandsgranska
  default_preview_prev_button_label: '< Föregående'
  default_preview_label: Förhandsgranska
  default_draft_button_label: 'Spara utkast'
  default_draft_saved_message: 'Formulär sparat. Du kan återvända till detta formulär senare och fortsätta inmatningen.'
  default_draft_loaded_message: '<p>A partially-completed form was found. Please complete the remaining portions.</p>'
  default_draft_pending_single_message: '<p>You have a pending draft for this webform. <a href="#">Load your pending draft</a>.</p>'
  default_draft_pending_multiple_message: '<p>You have pending drafts for this webform. <a href="#">View your pending drafts</a>.</p>'
  default_submission_access_denied_message: '<p>Please login to access this submission.</p>'
  default_submission_exception_message: '<p>Unable to process this submission. Please contact the site administrator.</p>'
  default_submission_locked_message: '<p>This submission has been locked.</p>'
  default_previous_submission_message: 'Du har redan skickat in detta formulär. <a href="#">Se ditt tidigare inlägg</a>.'
  default_previous_submissions_message: '<p>You have already submitted this webform. <a href="#">View your previous submissions</a>.</p>'
  default_autofill_message: '<p>This submission has been autofilled with your previous submission.</p>'
  default_limit_total_message: '<p>No more submissions are permitted.</p>'
  default_limit_user_message: '<p>No more submissions are permitted.</p>'
  dialog_options:
    narrow:
      title: Smal
    wide:
      title: Bred
element:
  default_more_title: Mer
file:
  file_private_redirect_message: 'Please login to access the uploaded file.'
