on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * 0'
name: Build scraping tool artifact
jobs:
  mirror:
    uses: city-of-helsinki/drupal-gh-actions/.github/workflows/scraping-tool.yml@main
    with:
      domain: 'historia.hel.fi'
