on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * 0'
name: Build Scarping tool artifact
jobs:
  build:
    uses: city-of-helsinki/drupal-gh-actions/.github/workflows/scraping-tool.yml@UHF-12546
    with:
      domain: 'historia.hel.fi'
